name: multisurv
channels:
  - pytorch
  - conda-forge
  - soumith
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - autograd=1.3=py_0
  - autograd-gamma=0.4.1=py_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h8022711_0
  - chardet=3.0.4=py36_1003
  - cloudpickle=1.2.2=py_1
  - cryptography=2.8=py36h72c5cf5_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.9.2=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - future=0.18.2=py36_0
  - gdk-pixbuf=2.32.2=1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.58.3=py36h6f030ca_1002
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - gobject-introspection=1.58.2=py36h5503ade_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_1000
  - imageio=2.6.1=py36_0
  - intel-openmp=2019.4=243
  - jasper=1.900.1=h07fcdf6_1006
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hc9558a2_0
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=15_openblas
  - libcblas=3.8.0=15_openblas
  - libclang=9.0.1=default_hde54327_0
  - libffi=3.2.1=he1b5a44_1006
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=15_openblas
  - liblapacke=3.8.0=15_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libopenblas=0.3.8=h5ec1e0e_0
  - libopencv=4.2.0=py36_2
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lifelines=0.23.8=py_0
  - llvm-openmp=9.0.1=hc9558a2_2
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.2=py36_1
  - matplotlib-base=3.1.2=py36h250f245_1
  - mkl=2020.0=166
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_0
  - ninja=1.10.0=hc9558a2_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py36h95a1406_0
  - olefile=0.46=py_0
  - opencv=4.2.0=py36_2
  - openh264=1.8.0=hdbcaa40_1000
  - openjpeg=2.3.1=h981e76c_3
  - openslide=3.4.1=2
  - openslide-python=1.1.1=py36h470a237_0
  - openssl=1.1.1d=h516909a_0
  - pandas=1.0.1=py36hb3f55d8_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.0.0=py36hefe7db6_0
  - pip=20.0.1=py36_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - py-opencv=4.2.0=py36h5ca1d4c_2
  - pycparser=2.19=py36_1
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py36hcca6a23_1
  - pysocks=1.7.1=py36_0
  - python=3.6.7=h357f687_1006
  - python-dateutil=2.8.1=py_0
  - pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36hc1659b7_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py36_1
  - scikit-image=0.16.2=py36hb3f55d8_0
  - scikit-learn=0.22.1=py36hcdab131_1
  - scipy=1.4.1=py36h921218d_0
  - six=1.14.0=py36_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py36_cu101
  - tornado=6.0.3=py36h516909a_0
  - urllib3=1.25.7=py36_0
  - wheel=0.33.6=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - cachetools==4.0.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - feather-format==0.4.0
    - gast==0.2.2
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.26.0
    - h5py==2.10.0
    - importlib-metadata==1.4.0
    - ipykernel==5.1.3
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.2
    - jinja2==2.10.3
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.1.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-core==4.6.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - llvmlite==0.31.0
    - lxml==4.4.2
    - markdown==3.1.1
    - markupsafe==1.1.1
    - mistune==0.8.4
    - more-itertools==8.1.0
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - notebook==6.0.3
    - numba==0.48.0
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - pandocfilters==1.4.2
    - parso==0.5.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - progressbar==2.5
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.2
    - protobuf==3.11.2
    - ptyprocess==0.6.0
    - pyarrow==0.15.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycox==0.2.0
    - pygments==2.5.2
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyrsistent==0.15.7
    - pysurvival==0.1.2
    - pyyaml==5.3
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - send2trash==1.5.0
    - setuptools==45.1.0
    - tensorboard==2.1.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - torchtuples==0.2.0
    - tqdm==4.43.0
    - traitlets==4.3.3
    - watermark==2.0.2
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - werkzeug==0.16.1
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - wsipre==0.1.2
    - zipp==2.0.1
prefix: /home/luis/anaconda3/envs/multisurv

